const STATUS = {
    AVAILABLE:'available'
}
const DOWNLOAD_IMAGE_SRC = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAS0lEQVR4nGNgGEngPxoetQAD/B8NIkLg/2gQoYNyLMGCC9cz0NCSenINJ8aSekoNx2cJ1QzHZgnVDYeBBigeBbQB/6mM6W8Bw5AEAO/6b2XgFcy5AAAAAElFTkSuQmCC"

const NO_DATA = 'No Data Available'
export {
    STATUS,
    DOWNLOAD_IMAGE_SRC,
    NO_DATA
}